apiVersion: v1
kind: ConfigMap
metadata:
  name: lacework-config
data:
  config.json: |
    {
      "tokens": {
        "AccessToken":"e8cfef21e694160b5e7a7a60c7d77a851d15eac0f81d683006a9424d"
        },
        "tags":{
          "Env":"k8s"
        },
        "serverurl":"https://api.lacework.net",
        "crioruntime": "enable"
        }
