apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: lacework-agent
    tier: monitoring
  name: lacework-agent
  namespace: lacework
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: datacollector
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: datacollector
    spec:
      containers:
      - image: lacework/datacollector-ubi8:latest
        imagePullPolicy: Always
        env:
          - name: LaceworkLogStdout
            value: "yes"
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/healthcheck.sh
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: datacollector
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/lacework/config
          name: cfgmap
        - mountPath: /dev
          name: dev
        - mountPath: /var/run/docker.sock
          name: run-sock
        - mountPath: /var/run/docker.pid
          name: run-pid
        - mountPath: /sys
          name: sys
        - mountPath: /var/log
          name: log
        - mountPath: /etc/passwd
          name: passwd
          readOnly: true
        - mountPath: /etc/group
          name: group
          readOnly: true
        - mountPath: /var/lib/lacework/collector
          name: hostlacework
        - mountPath: /laceworkfim
          name: hostroot
          readOnly: true
        - mountPath: /etc/podinfo
          name: podinfo
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: lacework
      serviceAccountName: lacework
      terminationGracePeriodSeconds: 20
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /dev
          type: ""
        name: dev
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: run-sock
      - hostPath:
          path: /var/run/docker.pid
          type: ""
        name: run-pid
      - hostPath:
          path: /sys
          type: ""
        name: sys
      - hostPath:
          path: /var/log
          type: ""
        name: log
      - hostPath:
          path: /etc/passwd
          type: ""
        name: passwd
      - hostPath:
          path: /etc/group
          type: ""
        name: group
      - hostPath:
          path: /
          type: ""
        name: hostroot
      - hostPath:
          path: /var/lib/lacework/collector
          type: ""
        name: hostlacework
      - configMap:
          defaultMode: 420
          items:
          - key: config.json
            path: config.json
          name: lacework-config
        name: cfgmap
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
